# Generated by Django 3.2.13 on 2022-05-17 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TendancePub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/media')),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.employe')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationAdmina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('somme', models.DecimalField(decimal_places=2, max_digits=19)),
                ('nature', models.CharField(choices=[('depot', 'depot'), ('retrait', 'retrait'), ('retrait code', 'retrait code'), ('envoi code', 'envoi code'), ('payement', 'payement'), ('activation', 'activation'), ('desactivation', 'desactivation'), ('reactivation', 'reactivation'), ('creation de compte business', 'creation de compte business'), ('creation de compte professionnel', 'creation de compte professionnel'), ('ajout de publicite', 'ajout de publicite'), ('nouveau membre staff', 'nouveau membre staff')], max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.CharField(max_length=255)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employe')),
            ],
        ),
        migrations.CreateModel(
            name='ActionStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nature', models.CharField(choices=[('depot', 'depot'), ('retrait', 'retrait'), ('retrait code', 'retrait code'), ('envoi code', 'envoi code'), ('payement', 'payement'), ('activation', 'activation'), ('desactivation', 'desactivation'), ('reactivation', 'reactivation'), ('creation de compte business', 'creation de compte business'), ('creation de compte professionnel', 'creation de compte professionnel'), ('ajout de publicite', 'ajout de publicite'), ('nouveau membre staff', 'nouveau membre staff')], max_length=255)),
                ('montant_rentrant', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('montant_entreprise', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.employe')),
            ],
        ),
    ]
