# Generated by Django 3.2.13 on 2022-08-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_qrcodeclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff_manager_personnel',
            field=models.BooleanField(default=False),
        ),
    ]
