# Generated by Django 3.2.13 on 2022-09-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_phoneverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneconfirmation',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
