# Generated by Django 3.2.13 on 2022-09-16 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20220916_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationtransaction',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.service'),
        ),
    ]
