# Generated by Django 3.2.13 on 2022-09-16 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_verificationtransaction_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Monaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monaie', models.CharField(max_length=255)),
                ('valeur_CFA', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
            ],
        ),
        migrations.AddField(
            model_name='transactionservice',
            name='employe_relever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.employe'),
        ),
        migrations.AddField(
            model_name='transactionservice',
            name='relever',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.pays'),
        ),
        migrations.AddField(
            model_name='pays',
            name='continent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.continent'),
        ),
        migrations.AddField(
            model_name='user',
            name='devise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.monaie'),
        ),
    ]
