# Generated by Django 3.2.13 on 2022-09-16 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20220916_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.service'),
        ),
        migrations.AddField(
            model_name='envoi',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.service'),
        ),
        migrations.AddField(
            model_name='retrait',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.service'),
        ),
        migrations.AddField(
            model_name='retraitcode',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.service'),
        ),
        migrations.AddField(
            model_name='viacode',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.service'),
        ),
        migrations.AlterField(
            model_name='depot',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.employe'),
        ),
        migrations.AlterField(
            model_name='retrait',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.employe'),
        ),
        migrations.AlterField(
            model_name='retraitcode',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.employe'),
        ),
    ]
