# Generated by Django 3.2.13 on 2022-09-17 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20220916_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='pays',
            name='monaie_associe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.monaie'),
        ),
    ]
