# Generated by Django 3.2.13 on 2022-09-17 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_pays_monaie_associe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='devise',
        ),
    ]
